### ISSUE TITLE
Editing Particular Equip Slots

### ISSUE THREAD

**Issue by pips-queek** [Synthlight/MHW-Editor#15]
In the armor.am_dat I would like to edit only the "charm" equip slot skills. Doing this by hand for every charm is cumbersome. Is there a way to define this variable with "*" via editing en mass?

{
  "targetFile": "armor.am_dat",
  "version": 3,
  "changesV3": {
    "Entries": {
	     "*": {
 INSERT CHANGES HERE
                   }
	           }
                   }
}

This works to edit EVERYTHING including armour.

I tried replacing "entries:" and then adding after "entries:"

 **"Charm":** 
and 
**"Equip Slot":**
     **"Charm":**

but it wouldnt change anything. Is my code incorrect or is there currently no way to define these variables in the .json files. 

Could this functionality be added?

**Comment by Synthlight** [comment]
The wildcard identifier is for the **row**, not filtered to anything else. It's currently all or nothing.
Adding `"Charm":` is just going to make invalid json. That's not how this is structured.
The `"Entries":` part is the structure in the file. The part below that is the row identifier of that struct.
Some file have multiple structures & some are even nested, but you can't use a column name in any way there.

The row identifier for `Armor.Entries` is `"{Set_Group}|{Variant}|{Type}|{Equip_Slot}"`. This way the armor position can move in the file & we can reference the right entry.
For example `"4|Low_Rank|Regular|Head"` since those are the **values** of the above formula.

The simplest change to make this work in the current system would be to allow the individual values to be wildcards.
So you'd wind up with something like `"*|*|*|Charm"`, but I'd have to add that in. Right now it's just all or nothing for wildcards.

**Comment by Synthlight** [comment]
Added to v2.3.
Easiest way to get the json right is to change one of the rows you want, export the change, and replace the one part of the identifier with a star.
You **must** preserver the same number of `|` in the id! If the quantity is different, it'll never match.

**Comment by Synthlight** [comment]
What I added to the wiki to describe it:

> You can set `*` as any row ID and it will apply to all rows.
You cal also set parts of the ID as wildcards: `4|Low_Rank|*|Head`. (Or even `*|*|*|*`, which is functionally equivalent to just `*`.)
Note that when doing the partial wildcard, you must have the **SAME** number of `|`!
You cannot do: `4|Low*lar|Head` or: `4|Low*Rank|Regular|Head`.
Either the whole thing is `*` or individual sections are. It will not work as a partial match within a word.
